language: cpp
compiler: gcc
dist: trusty

before_install:
  # submodule
  - git submodule update --init
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # CMake
  - sudo apt-get install -qq cmake
  # GTest
  - sudo apt-get install -qq libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  # copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
  - sudo cp *.a /usr/lib
  - cd -

script: 
  - cmake .
  - cmake --build . -- -j2
  - ctest
